version: '2'
services:
  write-db:
    image: 'mysql/mysql-server:latest'
    ports:
      - '3333:3306'
    volumes:
      - 'mysql_write_data:/bitnami'
    environment:
      MYSQL_REPLICATION_MODE: write
      MYSQL_REPLICATION_USER: root
      MYSQL_REPLICATION_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: crud
      MYSQL_PASSWORD: crud
      MYSQL_DATABASE: schema
      ALLOW_EMPTY_PASSWORD: "yes"
  read-db:
    image: 'mysql/mysql-server:latest'
    ports:
     - '3334:3306'
    depends_on:
     - db
    environment:
      MYSQL_REPLICATION_MODE: read
      MYSQL_REPLICATION_USER: root
      MYSQL_REPLICATION_PASSWORD: root
      MYSQL_MASTER_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: crud
      MYSQL_PASSWORD: crud
      MYSQL_DATABASE: schema
      MYSQL_MASTER_HOST: write-db
      MYSQL_MASTER_PORT_NUMBER: 3306
      ALLOW_EMPTY_PASSWORD: "yes"
volumes:
  mysql_write_data:
    driver: local