spring:
  application:
    name: learn-dubbo-provider
dubbo:
  application:
    name: learn-dubbo-provider
  protocol:
    name: dubbo
    port: ${LEARN_DUBBO_PROVIDER_PORT}
  registry:
    id: zk-registry
    protocol: zookeeper
    address: localhost:2181
    # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
  #    register-mode: instance
  provider:
    filter: metrics
  config-center:
    protocol: \${dubbo.registry.protocol}
    address: \${dubbo.registry.address}
  metadata-report:
    protocol: \${dubbo.registry.protocol}
    address: \${dubbo.registry.address}
  metrics:
    protocol: \${dubbo.protocol.name}
    port: \${dubbo.protocol.port}
